// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: timeline.proto
// Protobuf Java Version: 4.34.1

package sentinel.timeline;

/**
 * Protobuf type {@code sentinel.timeline.TimelineEntry}
 */
@com.google.protobuf.Generated
public final class TimelineEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.timeline.TimelineEntry)
    TimelineEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TimelineEntry");
  }
  // Use TimelineEntry.newBuilder() to construct.
  private TimelineEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimelineEntry() {
    entityId_ = "";
    entityType_ = "";
    eventType_ = "";
    snapshot_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.timeline.TimelineEntry.class, sentinel.timeline.TimelineEntry.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private long version_ = 0L;
  /**
   * <code>int64 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private sentinel.common.Timestamp timestamp_;
  /**
   * <code>.sentinel.common.Timestamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.common.Timestamp timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public sentinel.common.Timestamp getTimestamp() {
    return timestamp_ == null ? sentinel.common.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.sentinel.common.Timestamp timestamp = 2;</code>
   */
  @java.lang.Override
  public sentinel.common.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? sentinel.common.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int ENTITY_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entityId_ = "";
  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  @java.lang.Override
  public java.lang.String getEntityId() {
    java.lang.Object ref = entityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityId_ = s;
      return s;
    }
  }
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityIdBytes() {
    java.lang.Object ref = entityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITY_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entityType_ = "";
  /**
   * <code>string entity_type = 4;</code>
   * @return The entityType.
   */
  @java.lang.Override
  public java.lang.String getEntityType() {
    java.lang.Object ref = entityType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entityType_ = s;
      return s;
    }
  }
  /**
   * <code>string entity_type = 4;</code>
   * @return The bytes for entityType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityTypeBytes() {
    java.lang.Object ref = entityType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <code>string event_type = 5;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string event_type = 5;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SNAPSHOT_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString snapshot_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes snapshot = 6;</code>
   * @return The snapshot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSnapshot() {
    return snapshot_;
  }

  public static final int COMPRESSED_SIZE_FIELD_NUMBER = 7;
  private int compressedSize_ = 0;
  /**
   * <code>int32 compressed_size = 7;</code>
   * @return The compressedSize.
   */
  @java.lang.Override
  public int getCompressedSize() {
    return compressedSize_;
  }

  public static final int ORIGINAL_SIZE_FIELD_NUMBER = 8;
  private int originalSize_ = 0;
  /**
   * <code>int32 original_size = 8;</code>
   * @return The originalSize.
   */
  @java.lang.Override
  public int getOriginalSize() {
    return originalSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0L) {
      output.writeInt64(1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entityId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, entityId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entityType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, entityType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, eventType_);
    }
    if (!snapshot_.isEmpty()) {
      output.writeBytes(6, snapshot_);
    }
    if (compressedSize_ != 0) {
      output.writeInt32(7, compressedSize_);
    }
    if (originalSize_ != 0) {
      output.writeInt32(8, originalSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, version_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entityId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, entityId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entityType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, entityType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, eventType_);
    }
    if (!snapshot_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, snapshot_);
    }
    if (compressedSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, compressedSize_);
    }
    if (originalSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, originalSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.timeline.TimelineEntry)) {
      return super.equals(obj);
    }
    sentinel.timeline.TimelineEntry other = (sentinel.timeline.TimelineEntry) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!getEntityId()
        .equals(other.getEntityId())) return false;
    if (!getEntityType()
        .equals(other.getEntityType())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getSnapshot()
        .equals(other.getSnapshot())) return false;
    if (getCompressedSize()
        != other.getCompressedSize()) return false;
    if (getOriginalSize()
        != other.getOriginalSize()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + ENTITY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEntityId().hashCode();
    hash = (37 * hash) + ENTITY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEntityType().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
    hash = (53 * hash) + getSnapshot().hashCode();
    hash = (37 * hash) + COMPRESSED_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getCompressedSize();
    hash = (37 * hash) + ORIGINAL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalSize();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.timeline.TimelineEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.timeline.TimelineEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.timeline.TimelineEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.timeline.TimelineEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.timeline.TimelineEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.timeline.TimelineEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.timeline.TimelineEntry)
      sentinel.timeline.TimelineEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.timeline.TimelineEntry.class, sentinel.timeline.TimelineEntry.Builder.class);
    }

    // Construct using sentinel.timeline.TimelineEntry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTimestampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      version_ = 0L;
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      entityId_ = "";
      entityType_ = "";
      eventType_ = "";
      snapshot_ = com.google.protobuf.ByteString.EMPTY;
      compressedSize_ = 0;
      originalSize_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineEntry_descriptor;
    }

    @java.lang.Override
    public sentinel.timeline.TimelineEntry getDefaultInstanceForType() {
      return sentinel.timeline.TimelineEntry.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.timeline.TimelineEntry build() {
      sentinel.timeline.TimelineEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.timeline.TimelineEntry buildPartial() {
      sentinel.timeline.TimelineEntry result = new sentinel.timeline.TimelineEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.timeline.TimelineEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.version_ = version_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.entityId_ = entityId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.entityType_ = entityType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.snapshot_ = snapshot_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.compressedSize_ = compressedSize_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.originalSize_ = originalSize_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.timeline.TimelineEntry) {
        return mergeFrom((sentinel.timeline.TimelineEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.timeline.TimelineEntry other) {
      if (other == sentinel.timeline.TimelineEntry.getDefaultInstance()) return this;
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (!other.getEntityId().isEmpty()) {
        entityId_ = other.entityId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEntityType().isEmpty()) {
        entityType_ = other.entityType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSnapshot().isEmpty()) {
        setSnapshot(other.getSnapshot());
      }
      if (other.getCompressedSize() != 0) {
        setCompressedSize(other.getCompressedSize());
      }
      if (other.getOriginalSize() != 0) {
        setOriginalSize(other.getOriginalSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              version_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  internalGetTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              entityId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              entityType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              snapshot_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              compressedSize_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              originalSize_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long version_ ;
    /**
     * <code>int64 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {

      version_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      version_ = 0L;
      onChanged();
      return this;
    }

    private sentinel.common.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    public sentinel.common.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? sentinel.common.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(sentinel.common.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        sentinel.common.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(sentinel.common.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          timestamp_ != null &&
          timestamp_ != sentinel.common.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000002);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public sentinel.common.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    public sentinel.common.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            sentinel.common.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.sentinel.common.Timestamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> 
        internalGetTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.lang.Object entityId_ = "";
    /**
     * <code>string entity_id = 3;</code>
     * @return The entityId.
     */
    public java.lang.String getEntityId() {
      java.lang.Object ref = entityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return The bytes for entityId.
     */
    public com.google.protobuf.ByteString
        getEntityIdBytes() {
      java.lang.Object ref = entityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entityId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityId() {
      entityId_ = getDefaultInstance().getEntityId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The bytes for entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entityId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object entityType_ = "";
    /**
     * <code>string entity_type = 4;</code>
     * @return The entityType.
     */
    public java.lang.String getEntityType() {
      java.lang.Object ref = entityType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entityType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string entity_type = 4;</code>
     * @return The bytes for entityType.
     */
    public com.google.protobuf.ByteString
        getEntityTypeBytes() {
      java.lang.Object ref = entityType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entity_type = 4;</code>
     * @param value The entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entityType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string entity_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityType() {
      entityType_ = getDefaultInstance().getEntityType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string entity_type = 4;</code>
     * @param value The bytes for entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entityType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <code>string event_type = 5;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_type = 5;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_type = 5;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 5;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString snapshot_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes snapshot = 6;</code>
     * @return The snapshot.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSnapshot() {
      return snapshot_;
    }
    /**
     * <code>bytes snapshot = 6;</code>
     * @param value The snapshot to set.
     * @return This builder for chaining.
     */
    public Builder setSnapshot(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      snapshot_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes snapshot = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapshot() {
      bitField0_ = (bitField0_ & ~0x00000020);
      snapshot_ = getDefaultInstance().getSnapshot();
      onChanged();
      return this;
    }

    private int compressedSize_ ;
    /**
     * <code>int32 compressed_size = 7;</code>
     * @return The compressedSize.
     */
    @java.lang.Override
    public int getCompressedSize() {
      return compressedSize_;
    }
    /**
     * <code>int32 compressed_size = 7;</code>
     * @param value The compressedSize to set.
     * @return This builder for chaining.
     */
    public Builder setCompressedSize(int value) {

      compressedSize_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 compressed_size = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressedSize() {
      bitField0_ = (bitField0_ & ~0x00000040);
      compressedSize_ = 0;
      onChanged();
      return this;
    }

    private int originalSize_ ;
    /**
     * <code>int32 original_size = 8;</code>
     * @return The originalSize.
     */
    @java.lang.Override
    public int getOriginalSize() {
      return originalSize_;
    }
    /**
     * <code>int32 original_size = 8;</code>
     * @param value The originalSize to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalSize(int value) {

      originalSize_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 original_size = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalSize() {
      bitField0_ = (bitField0_ & ~0x00000080);
      originalSize_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.timeline.TimelineEntry)
  }

  // @@protoc_insertion_point(class_scope:sentinel.timeline.TimelineEntry)
  private static final sentinel.timeline.TimelineEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.timeline.TimelineEntry();
  }

  public static sentinel.timeline.TimelineEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimelineEntry>
      PARSER = new com.google.protobuf.AbstractParser<TimelineEntry>() {
    @java.lang.Override
    public TimelineEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TimelineEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimelineEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.timeline.TimelineEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

