// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: timeline.proto
// Protobuf Java Version: 4.34.1

package sentinel.timeline;

@com.google.protobuf.Generated
public final class Timeline extends com.google.protobuf.GeneratedFile {
  private Timeline() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Timeline");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_TimelineEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_TimelineEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_TimelineQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_TimelineQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_TimelineResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_TimelineResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_RecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_RecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_RecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_RecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_ReplayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_ReplayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_timeline_ReplayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_timeline_ReplayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016timeline.proto\022\021sentinel.timeline\032\014com" +
      "mon.proto\"\315\001\n\rTimelineEntry\022\017\n\007version\030\001" +
      " \001(\003\022-\n\ttimestamp\030\002 \001(\0132\032.sentinel.commo" +
      "n.Timestamp\022\021\n\tentity_id\030\003 \001(\t\022\023\n\013entity" +
      "_type\030\004 \001(\t\022\022\n\nevent_type\030\005 \001(\t\022\020\n\010snaps" +
      "hot\030\006 \001(\014\022\027\n\017compressed_size\030\007 \001(\005\022\025\n\ror" +
      "iginal_size\030\010 \001(\005\"\253\001\n\rTimelineQuery\022)\n\005s" +
      "tart\030\001 \001(\0132\032.sentinel.common.Timestamp\022\'" +
      "\n\003end\030\002 \001(\0132\032.sentinel.common.Timestamp\022" +
      "\022\n\nentity_ids\030\003 \003(\t\022\023\n\013event_types\030\004 \003(\t" +
      "\022\r\n\005limit\030\005 \001(\005\022\016\n\006offset\030\006 \001(\005\"R\n\016Timel" +
      "ineResult\0221\n\007entries\030\001 \003(\0132 .sentinel.ti" +
      "meline.TimelineEntry\022\r\n\005total\030\002 \001(\005\"@\n\rR" +
      "ecordRequest\022/\n\005entry\030\001 \001(\0132 .sentinel.t" +
      "imeline.TimelineEntry\"\"\n\016RecordResponse\022" +
      "\020\n\010recorded\030\001 \001(\010\"N\n\rReplayRequest\022\024\n\014fr" +
      "om_version\030\001 \001(\003\022\022\n\nto_version\030\002 \001(\003\022\023\n\013" +
      "interval_ms\030\003 \001(\005\"A\n\016ReplayResponse\022/\n\005e" +
      "ntry\030\001 \001(\0132 .sentinel.timeline.TimelineE" +
      "ntry2\377\001\n\017TimelineService\022M\n\006Record\022 .sen" +
      "tinel.timeline.RecordRequest\032!.sentinel." +
      "timeline.RecordResponse\022L\n\005Query\022 .senti" +
      "nel.timeline.TimelineQuery\032!.sentinel.ti" +
      "meline.TimelineResult\022O\n\006Replay\022 .sentin" +
      "el.timeline.ReplayRequest\032!.sentinel.tim" +
      "eline.ReplayResponse0\001BI\n\021sentinel.timel" +
      "ineP\001Z2github.com/sentinel/services/go/p" +
      "kg/proto/timelineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sentinel.common.Common.getDescriptor(),
        });
    internal_static_sentinel_timeline_TimelineEntry_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sentinel_timeline_TimelineEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_TimelineEntry_descriptor,
        new java.lang.String[] { "Version", "Timestamp", "EntityId", "EntityType", "EventType", "Snapshot", "CompressedSize", "OriginalSize", });
    internal_static_sentinel_timeline_TimelineQuery_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sentinel_timeline_TimelineQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_TimelineQuery_descriptor,
        new java.lang.String[] { "Start", "End", "EntityIds", "EventTypes", "Limit", "Offset", });
    internal_static_sentinel_timeline_TimelineResult_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sentinel_timeline_TimelineResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_TimelineResult_descriptor,
        new java.lang.String[] { "Entries", "Total", });
    internal_static_sentinel_timeline_RecordRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sentinel_timeline_RecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_RecordRequest_descriptor,
        new java.lang.String[] { "Entry", });
    internal_static_sentinel_timeline_RecordResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sentinel_timeline_RecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_RecordResponse_descriptor,
        new java.lang.String[] { "Recorded", });
    internal_static_sentinel_timeline_ReplayRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sentinel_timeline_ReplayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_ReplayRequest_descriptor,
        new java.lang.String[] { "FromVersion", "ToVersion", "IntervalMs", });
    internal_static_sentinel_timeline_ReplayResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_sentinel_timeline_ReplayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_timeline_ReplayResponse_descriptor,
        new java.lang.String[] { "Entry", });
    descriptor.resolveAllFeaturesImmutable();
    sentinel.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
