// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: timeline.proto
// Protobuf Java Version: 4.34.1

package sentinel.timeline;

/**
 * Protobuf type {@code sentinel.timeline.TimelineQuery}
 */
@com.google.protobuf.Generated
public final class TimelineQuery extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.timeline.TimelineQuery)
    TimelineQueryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TimelineQuery");
  }
  // Use TimelineQuery.newBuilder() to construct.
  private TimelineQuery(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TimelineQuery() {
    entityIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    eventTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.timeline.TimelineQuery.class, sentinel.timeline.TimelineQuery.Builder.class);
  }

  private int bitField0_;
  public static final int START_FIELD_NUMBER = 1;
  private sentinel.common.Timestamp start_;
  /**
   * <code>.sentinel.common.Timestamp start = 1;</code>
   * @return Whether the start field is set.
   */
  @java.lang.Override
  public boolean hasStart() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.common.Timestamp start = 1;</code>
   * @return The start.
   */
  @java.lang.Override
  public sentinel.common.Timestamp getStart() {
    return start_ == null ? sentinel.common.Timestamp.getDefaultInstance() : start_;
  }
  /**
   * <code>.sentinel.common.Timestamp start = 1;</code>
   */
  @java.lang.Override
  public sentinel.common.TimestampOrBuilder getStartOrBuilder() {
    return start_ == null ? sentinel.common.Timestamp.getDefaultInstance() : start_;
  }

  public static final int END_FIELD_NUMBER = 2;
  private sentinel.common.Timestamp end_;
  /**
   * <code>.sentinel.common.Timestamp end = 2;</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.sentinel.common.Timestamp end = 2;</code>
   * @return The end.
   */
  @java.lang.Override
  public sentinel.common.Timestamp getEnd() {
    return end_ == null ? sentinel.common.Timestamp.getDefaultInstance() : end_;
  }
  /**
   * <code>.sentinel.common.Timestamp end = 2;</code>
   */
  @java.lang.Override
  public sentinel.common.TimestampOrBuilder getEndOrBuilder() {
    return end_ == null ? sentinel.common.Timestamp.getDefaultInstance() : end_;
  }

  public static final int ENTITY_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList entityIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string entity_ids = 3;</code>
   * @return A list containing the entityIds.
   */
  public com.google.protobuf.ProtocolStringList
      getEntityIdsList() {
    return entityIds_;
  }
  /**
   * <code>repeated string entity_ids = 3;</code>
   * @return The count of entityIds.
   */
  public int getEntityIdsCount() {
    return entityIds_.size();
  }
  /**
   * <code>repeated string entity_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The entityIds at the given index.
   */
  public java.lang.String getEntityIds(int index) {
    return entityIds_.get(index);
  }
  /**
   * <code>repeated string entity_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the entityIds at the given index.
   */
  public com.google.protobuf.ByteString
      getEntityIdsBytes(int index) {
    return entityIds_.getByteString(index);
  }

  public static final int EVENT_TYPES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList eventTypes_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string event_types = 4;</code>
   * @return A list containing the eventTypes.
   */
  public com.google.protobuf.ProtocolStringList
      getEventTypesList() {
    return eventTypes_;
  }
  /**
   * <code>repeated string event_types = 4;</code>
   * @return The count of eventTypes.
   */
  public int getEventTypesCount() {
    return eventTypes_.size();
  }
  /**
   * <code>repeated string event_types = 4;</code>
   * @param index The index of the element to return.
   * @return The eventTypes at the given index.
   */
  public java.lang.String getEventTypes(int index) {
    return eventTypes_.get(index);
  }
  /**
   * <code>repeated string event_types = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the eventTypes at the given index.
   */
  public com.google.protobuf.ByteString
      getEventTypesBytes(int index) {
    return eventTypes_.getByteString(index);
  }

  public static final int LIMIT_FIELD_NUMBER = 5;
  private int limit_ = 0;
  /**
   * <code>int32 limit = 5;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  public static final int OFFSET_FIELD_NUMBER = 6;
  private int offset_ = 0;
  /**
   * <code>int32 offset = 6;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStart());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getEnd());
    }
    for (int i = 0; i < entityIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, entityIds_.getRaw(i));
    }
    for (int i = 0; i < eventTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, eventTypes_.getRaw(i));
    }
    if (limit_ != 0) {
      output.writeInt32(5, limit_);
    }
    if (offset_ != 0) {
      output.writeInt32(6, offset_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStart());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEnd());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < entityIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(entityIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEntityIdsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < eventTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(eventTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getEventTypesList().size();
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, limit_);
    }
    if (offset_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, offset_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.timeline.TimelineQuery)) {
      return super.equals(obj);
    }
    sentinel.timeline.TimelineQuery other = (sentinel.timeline.TimelineQuery) obj;

    if (hasStart() != other.hasStart()) return false;
    if (hasStart()) {
      if (!getStart()
          .equals(other.getStart())) return false;
    }
    if (hasEnd() != other.hasEnd()) return false;
    if (hasEnd()) {
      if (!getEnd()
          .equals(other.getEnd())) return false;
    }
    if (!getEntityIdsList()
        .equals(other.getEntityIdsList())) return false;
    if (!getEventTypesList()
        .equals(other.getEventTypesList())) return false;
    if (getLimit()
        != other.getLimit()) return false;
    if (getOffset()
        != other.getOffset()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStart()) {
      hash = (37 * hash) + START_FIELD_NUMBER;
      hash = (53 * hash) + getStart().hashCode();
    }
    if (hasEnd()) {
      hash = (37 * hash) + END_FIELD_NUMBER;
      hash = (53 * hash) + getEnd().hashCode();
    }
    if (getEntityIdsCount() > 0) {
      hash = (37 * hash) + ENTITY_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getEntityIdsList().hashCode();
    }
    if (getEventTypesCount() > 0) {
      hash = (37 * hash) + EVENT_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getEventTypesList().hashCode();
    }
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    hash = (37 * hash) + OFFSET_FIELD_NUMBER;
    hash = (53 * hash) + getOffset();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.timeline.TimelineQuery parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.timeline.TimelineQuery parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.timeline.TimelineQuery parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.timeline.TimelineQuery parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.timeline.TimelineQuery prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.timeline.TimelineQuery}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.timeline.TimelineQuery)
      sentinel.timeline.TimelineQueryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.timeline.TimelineQuery.class, sentinel.timeline.TimelineQuery.Builder.class);
    }

    // Construct using sentinel.timeline.TimelineQuery.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetStartFieldBuilder();
        internalGetEndFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      entityIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      eventTypes_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      limit_ = 0;
      offset_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.timeline.Timeline.internal_static_sentinel_timeline_TimelineQuery_descriptor;
    }

    @java.lang.Override
    public sentinel.timeline.TimelineQuery getDefaultInstanceForType() {
      return sentinel.timeline.TimelineQuery.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.timeline.TimelineQuery build() {
      sentinel.timeline.TimelineQuery result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.timeline.TimelineQuery buildPartial() {
      sentinel.timeline.TimelineQuery result = new sentinel.timeline.TimelineQuery(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.timeline.TimelineQuery result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.start_ = startBuilder_ == null
            ? start_
            : startBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.end_ = endBuilder_ == null
            ? end_
            : endBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        entityIds_.makeImmutable();
        result.entityIds_ = entityIds_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        eventTypes_.makeImmutable();
        result.eventTypes_ = eventTypes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.limit_ = limit_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.offset_ = offset_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.timeline.TimelineQuery) {
        return mergeFrom((sentinel.timeline.TimelineQuery)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.timeline.TimelineQuery other) {
      if (other == sentinel.timeline.TimelineQuery.getDefaultInstance()) return this;
      if (other.hasStart()) {
        mergeStart(other.getStart());
      }
      if (other.hasEnd()) {
        mergeEnd(other.getEnd());
      }
      if (!other.entityIds_.isEmpty()) {
        if (entityIds_.isEmpty()) {
          entityIds_ = other.entityIds_;
          bitField0_ |= 0x00000004;
        } else {
          ensureEntityIdsIsMutable();
          entityIds_.addAll(other.entityIds_);
        }
        onChanged();
      }
      if (!other.eventTypes_.isEmpty()) {
        if (eventTypes_.isEmpty()) {
          eventTypes_ = other.eventTypes_;
          bitField0_ |= 0x00000008;
        } else {
          ensureEventTypesIsMutable();
          eventTypes_.addAll(other.eventTypes_);
        }
        onChanged();
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      if (other.getOffset() != 0) {
        setOffset(other.getOffset());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetEndFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ensureEntityIdsIsMutable();
              entityIds_.add(input.readStringRequireUtf8());
              break;
            } // case 26
            case 34: {
              ensureEventTypesIsMutable();
              eventTypes_.add(input.readStringRequireUtf8());
              break;
            } // case 34
            case 40: {
              limit_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              offset_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private sentinel.common.Timestamp start_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> startBuilder_;
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     * @return Whether the start field is set.
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     * @return The start.
     */
    public sentinel.common.Timestamp getStart() {
      if (startBuilder_ == null) {
        return start_ == null ? sentinel.common.Timestamp.getDefaultInstance() : start_;
      } else {
        return startBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public Builder setStart(sentinel.common.Timestamp value) {
      if (startBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        start_ = value;
      } else {
        startBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public Builder setStart(
        sentinel.common.Timestamp.Builder builderForValue) {
      if (startBuilder_ == null) {
        start_ = builderForValue.build();
      } else {
        startBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public Builder mergeStart(sentinel.common.Timestamp value) {
      if (startBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          start_ != null &&
          start_ != sentinel.common.Timestamp.getDefaultInstance()) {
          getStartBuilder().mergeFrom(value);
        } else {
          start_ = value;
        }
      } else {
        startBuilder_.mergeFrom(value);
      }
      if (start_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public Builder clearStart() {
      bitField0_ = (bitField0_ & ~0x00000001);
      start_ = null;
      if (startBuilder_ != null) {
        startBuilder_.dispose();
        startBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public sentinel.common.Timestamp.Builder getStartBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetStartFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    public sentinel.common.TimestampOrBuilder getStartOrBuilder() {
      if (startBuilder_ != null) {
        return startBuilder_.getMessageOrBuilder();
      } else {
        return start_ == null ?
            sentinel.common.Timestamp.getDefaultInstance() : start_;
      }
    }
    /**
     * <code>.sentinel.common.Timestamp start = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> 
        internalGetStartFieldBuilder() {
      if (startBuilder_ == null) {
        startBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder>(
                getStart(),
                getParentForChildren(),
                isClean());
        start_ = null;
      }
      return startBuilder_;
    }

    private sentinel.common.Timestamp end_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> endBuilder_;
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     * @return Whether the end field is set.
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     * @return The end.
     */
    public sentinel.common.Timestamp getEnd() {
      if (endBuilder_ == null) {
        return end_ == null ? sentinel.common.Timestamp.getDefaultInstance() : end_;
      } else {
        return endBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public Builder setEnd(sentinel.common.Timestamp value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        end_ = value;
      } else {
        endBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public Builder setEnd(
        sentinel.common.Timestamp.Builder builderForValue) {
      if (endBuilder_ == null) {
        end_ = builderForValue.build();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public Builder mergeEnd(sentinel.common.Timestamp value) {
      if (endBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          end_ != null &&
          end_ != sentinel.common.Timestamp.getDefaultInstance()) {
          getEndBuilder().mergeFrom(value);
        } else {
          end_ = value;
        }
      } else {
        endBuilder_.mergeFrom(value);
      }
      if (end_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public Builder clearEnd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      end_ = null;
      if (endBuilder_ != null) {
        endBuilder_.dispose();
        endBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public sentinel.common.Timestamp.Builder getEndBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    public sentinel.common.TimestampOrBuilder getEndOrBuilder() {
      if (endBuilder_ != null) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        return end_ == null ?
            sentinel.common.Timestamp.getDefaultInstance() : end_;
      }
    }
    /**
     * <code>.sentinel.common.Timestamp end = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> 
        internalGetEndFieldBuilder() {
      if (endBuilder_ == null) {
        endBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder>(
                getEnd(),
                getParentForChildren(),
                isClean());
        end_ = null;
      }
      return endBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList entityIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureEntityIdsIsMutable() {
      if (!entityIds_.isModifiable()) {
        entityIds_ = new com.google.protobuf.LazyStringArrayList(entityIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @return A list containing the entityIds.
     */
    public com.google.protobuf.ProtocolStringList
        getEntityIdsList() {
      entityIds_.makeImmutable();
      return entityIds_;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @return The count of entityIds.
     */
    public int getEntityIdsCount() {
      return entityIds_.size();
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The entityIds at the given index.
     */
    public java.lang.String getEntityIds(int index) {
      return entityIds_.get(index);
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the entityIds at the given index.
     */
    public com.google.protobuf.ByteString
        getEntityIdsBytes(int index) {
      return entityIds_.getByteString(index);
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The entityIds to set.
     * @return This builder for chaining.
     */
    public Builder setEntityIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEntityIdsIsMutable();
      entityIds_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param value The entityIds to add.
     * @return This builder for chaining.
     */
    public Builder addEntityIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEntityIdsIsMutable();
      entityIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param values The entityIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllEntityIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureEntityIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, entityIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityIds() {
      entityIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string entity_ids = 3;</code>
     * @param value The bytes of the entityIds to add.
     * @return This builder for chaining.
     */
    public Builder addEntityIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEntityIdsIsMutable();
      entityIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList eventTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureEventTypesIsMutable() {
      if (!eventTypes_.isModifiable()) {
        eventTypes_ = new com.google.protobuf.LazyStringArrayList(eventTypes_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @return A list containing the eventTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getEventTypesList() {
      eventTypes_.makeImmutable();
      return eventTypes_;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @return The count of eventTypes.
     */
    public int getEventTypesCount() {
      return eventTypes_.size();
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param index The index of the element to return.
     * @return The eventTypes at the given index.
     */
    public java.lang.String getEventTypes(int index) {
      return eventTypes_.get(index);
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the eventTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getEventTypesBytes(int index) {
      return eventTypes_.getByteString(index);
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param index The index to set the value at.
     * @param value The eventTypes to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypes(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventTypesIsMutable();
      eventTypes_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param value The eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addEventTypes(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureEventTypesIsMutable();
      eventTypes_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param values The eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureEventTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, eventTypes_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTypes() {
      eventTypes_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string event_types = 4;</code>
     * @param value The bytes of the eventTypes to add.
     * @return This builder for chaining.
     */
    public Builder addEventTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureEventTypesIsMutable();
      eventTypes_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <code>int32 limit = 5;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>int32 limit = 5;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {

      limit_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 limit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000010);
      limit_ = 0;
      onChanged();
      return this;
    }

    private int offset_ ;
    /**
     * <code>int32 offset = 6;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return offset_;
    }
    /**
     * <code>int32 offset = 6;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {

      offset_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 offset = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      bitField0_ = (bitField0_ & ~0x00000020);
      offset_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.timeline.TimelineQuery)
  }

  // @@protoc_insertion_point(class_scope:sentinel.timeline.TimelineQuery)
  private static final sentinel.timeline.TimelineQuery DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.timeline.TimelineQuery();
  }

  public static sentinel.timeline.TimelineQuery getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TimelineQuery>
      PARSER = new com.google.protobuf.AbstractParser<TimelineQuery>() {
    @java.lang.Override
    public TimelineQuery parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TimelineQuery> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TimelineQuery> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.timeline.TimelineQuery getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

