// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: timeline.proto
// Protobuf Java Version: 4.34.1

package sentinel.timeline;

@com.google.protobuf.Generated
public interface TimelineResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.timeline.TimelineResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .sentinel.timeline.TimelineEntry entries = 1;</code>
   */
  java.util.List<sentinel.timeline.TimelineEntry> 
      getEntriesList();
  /**
   * <code>repeated .sentinel.timeline.TimelineEntry entries = 1;</code>
   */
  sentinel.timeline.TimelineEntry getEntries(int index);
  /**
   * <code>repeated .sentinel.timeline.TimelineEntry entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .sentinel.timeline.TimelineEntry entries = 1;</code>
   */
  java.util.List<? extends sentinel.timeline.TimelineEntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .sentinel.timeline.TimelineEntry entries = 1;</code>
   */
  sentinel.timeline.TimelineEntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();
}
