// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.34.1

package sentinel.common;

@com.google.protobuf.Generated
public interface MetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.common.Metadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>map&lt;string, string&gt; entries = 1;</code>
   */
  boolean containsEntries(
      java.lang.String key);
  /**
   * Use {@link #getEntriesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEntries();
  /**
   * <code>map&lt;string, string&gt; entries = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEntriesMap();
  /**
   * <code>map&lt;string, string&gt; entries = 1;</code>
   */
  /* nullable */
java.lang.String getEntriesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; entries = 1;</code>
   */
  java.lang.String getEntriesOrThrow(
      java.lang.String key);
}
