// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: events.proto

package events

import (
	common "github.com/sentinel/services/go/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_WORKER_MOVED           EventType = 1
	EventType_SENSOR_UPDATED         EventType = 2
	EventType_HAZARD_DETECTED        EventType = 3
	EventType_HAZARD_CLEARED         EventType = 4
	EventType_RISK_EVALUATED         EventType = 5
	EventType_VIOLATION_DETECTED     EventType = 6
	EventType_PREDICTION_GENERATED   EventType = 7
	EventType_PLAN_RECOMMENDED       EventType = 8
	EventType_SIMULATION_TICK        EventType = 9
	EventType_ALERT_TRIGGERED        EventType = 10
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "WORKER_MOVED",
		2:  "SENSOR_UPDATED",
		3:  "HAZARD_DETECTED",
		4:  "HAZARD_CLEARED",
		5:  "RISK_EVALUATED",
		6:  "VIOLATION_DETECTED",
		7:  "PREDICTION_GENERATED",
		8:  "PLAN_RECOMMENDED",
		9:  "SIMULATION_TICK",
		10: "ALERT_TRIGGERED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"WORKER_MOVED":           1,
		"SENSOR_UPDATED":         2,
		"HAZARD_DETECTED":        3,
		"HAZARD_CLEARED":         4,
		"RISK_EVALUATED":         5,
		"VIOLATION_DETECTED":     6,
		"PREDICTION_GENERATED":   7,
		"PLAN_RECOMMENDED":       8,
		"SIMULATION_TICK":        9,
		"ALERT_TRIGGERED":        10,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=type,proto3,enum=sentinel.events.EventType" json:"type,omitempty"`
	Timestamp     *common.Timestamp      `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	PlantId       string                 `protobuf:"bytes,5,opt,name=plant_id,json=plantId,proto3" json:"plant_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      *common.Metadata       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetTimestamp() *common.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetPlantId() string {
	if x != nil {
		return x.PlantId
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetadata() *common.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x0fsentinel.events\x1a\fcommon.proto\"\x85\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.sentinel.events.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.sentinel.common.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x19\n" +
	"\bplant_id\x18\x05 \x01(\tR\aplantId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x125\n" +
	"\bmetadata\x18\a \x01(\v2\x19.sentinel.common.MetadataR\bmetadata\"R\n" +
	"\n" +
	"EventBatch\x12.\n" +
	"\x06events\x18\x01 \x03(\v2\x16.sentinel.events.EventR\x06events\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count*\xfc\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fWORKER_MOVED\x10\x01\x12\x12\n" +
	"\x0eSENSOR_UPDATED\x10\x02\x12\x13\n" +
	"\x0fHAZARD_DETECTED\x10\x03\x12\x12\n" +
	"\x0eHAZARD_CLEARED\x10\x04\x12\x12\n" +
	"\x0eRISK_EVALUATED\x10\x05\x12\x16\n" +
	"\x12VIOLATION_DETECTED\x10\x06\x12\x18\n" +
	"\x14PREDICTION_GENERATED\x10\a\x12\x14\n" +
	"\x10PLAN_RECOMMENDED\x10\b\x12\x13\n" +
	"\x0fSIMULATION_TICK\x10\t\x12\x13\n" +
	"\x0fALERT_TRIGGERED\x10\n" +
	"B2Z0github.com/sentinel/services/go/pkg/proto/eventsb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_proto_goTypes = []any{
	(EventType)(0),           // 0: sentinel.events.EventType
	(*Event)(nil),            // 1: sentinel.events.Event
	(*EventBatch)(nil),       // 2: sentinel.events.EventBatch
	(*common.Timestamp)(nil), // 3: sentinel.common.Timestamp
	(*common.Metadata)(nil),  // 4: sentinel.common.Metadata
}
var file_events_proto_depIdxs = []int32{
	0, // 0: sentinel.events.Event.type:type_name -> sentinel.events.EventType
	3, // 1: sentinel.events.Event.timestamp:type_name -> sentinel.common.Timestamp
	4, // 2: sentinel.events.Event.metadata:type_name -> sentinel.common.Metadata
	1, // 3: sentinel.events.EventBatch.events:type_name -> sentinel.events.Event
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
