// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: world.proto
// Protobuf Java Version: 4.34.1

package sentinel.world;

/**
 * Protobuf type {@code sentinel.world.GetSnapshotResponse}
 */
@com.google.protobuf.Generated
public final class GetSnapshotResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.world.GetSnapshotResponse)
    GetSnapshotResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "GetSnapshotResponse");
  }
  // Use GetSnapshotResponse.newBuilder() to construct.
  private GetSnapshotResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetSnapshotResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.world.GetSnapshotResponse.class, sentinel.world.GetSnapshotResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SNAPSHOT_FIELD_NUMBER = 1;
  private sentinel.world.WorldSnapshot snapshot_;
  /**
   * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
   * @return Whether the snapshot field is set.
   */
  @java.lang.Override
  public boolean hasSnapshot() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
   * @return The snapshot.
   */
  @java.lang.Override
  public sentinel.world.WorldSnapshot getSnapshot() {
    return snapshot_ == null ? sentinel.world.WorldSnapshot.getDefaultInstance() : snapshot_;
  }
  /**
   * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
   */
  @java.lang.Override
  public sentinel.world.WorldSnapshotOrBuilder getSnapshotOrBuilder() {
    return snapshot_ == null ? sentinel.world.WorldSnapshot.getDefaultInstance() : snapshot_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSnapshot());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSnapshot());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.world.GetSnapshotResponse)) {
      return super.equals(obj);
    }
    sentinel.world.GetSnapshotResponse other = (sentinel.world.GetSnapshotResponse) obj;

    if (hasSnapshot() != other.hasSnapshot()) return false;
    if (hasSnapshot()) {
      if (!getSnapshot()
          .equals(other.getSnapshot())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSnapshot()) {
      hash = (37 * hash) + SNAPSHOT_FIELD_NUMBER;
      hash = (53 * hash) + getSnapshot().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.world.GetSnapshotResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.world.GetSnapshotResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.world.GetSnapshotResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.GetSnapshotResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.world.GetSnapshotResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.world.GetSnapshotResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.world.GetSnapshotResponse)
      sentinel.world.GetSnapshotResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.world.GetSnapshotResponse.class, sentinel.world.GetSnapshotResponse.Builder.class);
    }

    // Construct using sentinel.world.GetSnapshotResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetSnapshotFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      snapshot_ = null;
      if (snapshotBuilder_ != null) {
        snapshotBuilder_.dispose();
        snapshotBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.world.World.internal_static_sentinel_world_GetSnapshotResponse_descriptor;
    }

    @java.lang.Override
    public sentinel.world.GetSnapshotResponse getDefaultInstanceForType() {
      return sentinel.world.GetSnapshotResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.world.GetSnapshotResponse build() {
      sentinel.world.GetSnapshotResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.world.GetSnapshotResponse buildPartial() {
      sentinel.world.GetSnapshotResponse result = new sentinel.world.GetSnapshotResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.world.GetSnapshotResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.snapshot_ = snapshotBuilder_ == null
            ? snapshot_
            : snapshotBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.world.GetSnapshotResponse) {
        return mergeFrom((sentinel.world.GetSnapshotResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.world.GetSnapshotResponse other) {
      if (other == sentinel.world.GetSnapshotResponse.getDefaultInstance()) return this;
      if (other.hasSnapshot()) {
        mergeSnapshot(other.getSnapshot());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetSnapshotFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private sentinel.world.WorldSnapshot snapshot_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.world.WorldSnapshot, sentinel.world.WorldSnapshot.Builder, sentinel.world.WorldSnapshotOrBuilder> snapshotBuilder_;
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     * @return Whether the snapshot field is set.
     */
    public boolean hasSnapshot() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     * @return The snapshot.
     */
    public sentinel.world.WorldSnapshot getSnapshot() {
      if (snapshotBuilder_ == null) {
        return snapshot_ == null ? sentinel.world.WorldSnapshot.getDefaultInstance() : snapshot_;
      } else {
        return snapshotBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public Builder setSnapshot(sentinel.world.WorldSnapshot value) {
      if (snapshotBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        snapshot_ = value;
      } else {
        snapshotBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public Builder setSnapshot(
        sentinel.world.WorldSnapshot.Builder builderForValue) {
      if (snapshotBuilder_ == null) {
        snapshot_ = builderForValue.build();
      } else {
        snapshotBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public Builder mergeSnapshot(sentinel.world.WorldSnapshot value) {
      if (snapshotBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          snapshot_ != null &&
          snapshot_ != sentinel.world.WorldSnapshot.getDefaultInstance()) {
          getSnapshotBuilder().mergeFrom(value);
        } else {
          snapshot_ = value;
        }
      } else {
        snapshotBuilder_.mergeFrom(value);
      }
      if (snapshot_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public Builder clearSnapshot() {
      bitField0_ = (bitField0_ & ~0x00000001);
      snapshot_ = null;
      if (snapshotBuilder_ != null) {
        snapshotBuilder_.dispose();
        snapshotBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public sentinel.world.WorldSnapshot.Builder getSnapshotBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetSnapshotFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    public sentinel.world.WorldSnapshotOrBuilder getSnapshotOrBuilder() {
      if (snapshotBuilder_ != null) {
        return snapshotBuilder_.getMessageOrBuilder();
      } else {
        return snapshot_ == null ?
            sentinel.world.WorldSnapshot.getDefaultInstance() : snapshot_;
      }
    }
    /**
     * <code>.sentinel.world.WorldSnapshot snapshot = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.world.WorldSnapshot, sentinel.world.WorldSnapshot.Builder, sentinel.world.WorldSnapshotOrBuilder> 
        internalGetSnapshotFieldBuilder() {
      if (snapshotBuilder_ == null) {
        snapshotBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.world.WorldSnapshot, sentinel.world.WorldSnapshot.Builder, sentinel.world.WorldSnapshotOrBuilder>(
                getSnapshot(),
                getParentForChildren(),
                isClean());
        snapshot_ = null;
      }
      return snapshotBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.world.GetSnapshotResponse)
  }

  // @@protoc_insertion_point(class_scope:sentinel.world.GetSnapshotResponse)
  private static final sentinel.world.GetSnapshotResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.world.GetSnapshotResponse();
  }

  public static sentinel.world.GetSnapshotResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSnapshotResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSnapshotResponse>() {
    @java.lang.Override
    public GetSnapshotResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetSnapshotResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSnapshotResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.world.GetSnapshotResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

