// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: world.proto
// Protobuf Java Version: 4.34.1

package sentinel.world;

/**
 * Protobuf type {@code sentinel.world.Hazard}
 */
@com.google.protobuf.Generated
public final class Hazard extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.world.Hazard)
    HazardOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Hazard");
  }
  // Use Hazard.newBuilder() to construct.
  private Hazard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Hazard() {
    id_ = "";
    hazardType_ = "";
    severity_ = "";
    zoneId_ = "";
    description_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.world.World.internal_static_sentinel_world_Hazard_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.world.World.internal_static_sentinel_world_Hazard_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.world.World.internal_static_sentinel_world_Hazard_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.world.Hazard.class, sentinel.world.Hazard.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HAZARD_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hazardType_ = "";
  /**
   * <code>string hazard_type = 2;</code>
   * @return The hazardType.
   */
  @java.lang.Override
  public java.lang.String getHazardType() {
    java.lang.Object ref = hazardType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hazardType_ = s;
      return s;
    }
  }
  /**
   * <code>string hazard_type = 2;</code>
   * @return The bytes for hazardType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHazardTypeBytes() {
    java.lang.Object ref = hazardType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hazardType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVERITY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object severity_ = "";
  /**
   * <code>string severity = 3;</code>
   * @return The severity.
   */
  @java.lang.Override
  public java.lang.String getSeverity() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      severity_ = s;
      return s;
    }
  }
  /**
   * <code>string severity = 3;</code>
   * @return The bytes for severity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSeverityBytes() {
    java.lang.Object ref = severity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      severity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ZONE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object zoneId_ = "";
  /**
   * <code>string zone_id = 4;</code>
   * @return The zoneId.
   */
  @java.lang.Override
  public java.lang.String getZoneId() {
    java.lang.Object ref = zoneId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      zoneId_ = s;
      return s;
    }
  }
  /**
   * <code>string zone_id = 4;</code>
   * @return The bytes for zoneId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getZoneIdBytes() {
    java.lang.Object ref = zoneId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      zoneId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int X_FIELD_NUMBER = 5;
  private double x_ = 0D;
  /**
   * <code>double x = 5;</code>
   * @return The x.
   */
  @java.lang.Override
  public double getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 6;
  private double y_ = 0D;
  /**
   * <code>double y = 6;</code>
   * @return The y.
   */
  @java.lang.Override
  public double getY() {
    return y_;
  }

  public static final int Z_FIELD_NUMBER = 7;
  private double z_ = 0D;
  /**
   * <code>double z = 7;</code>
   * @return The z.
   */
  @java.lang.Override
  public double getZ() {
    return z_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 8;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 8;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETECTED_AT_FIELD_NUMBER = 9;
  private sentinel.common.Timestamp detectedAt_;
  /**
   * <code>.sentinel.common.Timestamp detected_at = 9;</code>
   * @return Whether the detectedAt field is set.
   */
  @java.lang.Override
  public boolean hasDetectedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.common.Timestamp detected_at = 9;</code>
   * @return The detectedAt.
   */
  @java.lang.Override
  public sentinel.common.Timestamp getDetectedAt() {
    return detectedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : detectedAt_;
  }
  /**
   * <code>.sentinel.common.Timestamp detected_at = 9;</code>
   */
  @java.lang.Override
  public sentinel.common.TimestampOrBuilder getDetectedAtOrBuilder() {
    return detectedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : detectedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hazardType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, hazardType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zoneId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, zoneId_);
    }
    if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
      output.writeDouble(5, x_);
    }
    if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
      output.writeDouble(6, y_);
    }
    if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
      output.writeDouble(7, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, description_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(9, getDetectedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hazardType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, hazardType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(severity_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, severity_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(zoneId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, zoneId_);
    }
    if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, x_);
    }
    if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, y_);
    }
    if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, z_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, description_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDetectedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.world.Hazard)) {
      return super.equals(obj);
    }
    sentinel.world.Hazard other = (sentinel.world.Hazard) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getHazardType()
        .equals(other.getHazardType())) return false;
    if (!getSeverity()
        .equals(other.getSeverity())) return false;
    if (!getZoneId()
        .equals(other.getZoneId())) return false;
    if (java.lang.Double.doubleToLongBits(getX())
        != java.lang.Double.doubleToLongBits(
            other.getX())) return false;
    if (java.lang.Double.doubleToLongBits(getY())
        != java.lang.Double.doubleToLongBits(
            other.getY())) return false;
    if (java.lang.Double.doubleToLongBits(getZ())
        != java.lang.Double.doubleToLongBits(
            other.getZ())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (hasDetectedAt() != other.hasDetectedAt()) return false;
    if (hasDetectedAt()) {
      if (!getDetectedAt()
          .equals(other.getDetectedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + HAZARD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getHazardType().hashCode();
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + getSeverity().hashCode();
    hash = (37 * hash) + ZONE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getZoneId().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getX()));
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getY()));
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZ()));
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (hasDetectedAt()) {
      hash = (37 * hash) + DETECTED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDetectedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.world.Hazard parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.Hazard parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.Hazard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.Hazard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.Hazard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.Hazard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.Hazard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.Hazard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.world.Hazard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.world.Hazard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.world.Hazard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.Hazard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.world.Hazard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.world.Hazard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.world.Hazard)
      sentinel.world.HazardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.world.World.internal_static_sentinel_world_Hazard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.world.World.internal_static_sentinel_world_Hazard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.world.Hazard.class, sentinel.world.Hazard.Builder.class);
    }

    // Construct using sentinel.world.Hazard.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDetectedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      hazardType_ = "";
      severity_ = "";
      zoneId_ = "";
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
      description_ = "";
      detectedAt_ = null;
      if (detectedAtBuilder_ != null) {
        detectedAtBuilder_.dispose();
        detectedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.world.World.internal_static_sentinel_world_Hazard_descriptor;
    }

    @java.lang.Override
    public sentinel.world.Hazard getDefaultInstanceForType() {
      return sentinel.world.Hazard.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.world.Hazard build() {
      sentinel.world.Hazard result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.world.Hazard buildPartial() {
      sentinel.world.Hazard result = new sentinel.world.Hazard(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.world.Hazard result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hazardType_ = hazardType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.severity_ = severity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.zoneId_ = zoneId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.z_ = z_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.description_ = description_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.detectedAt_ = detectedAtBuilder_ == null
            ? detectedAt_
            : detectedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.world.Hazard) {
        return mergeFrom((sentinel.world.Hazard)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.world.Hazard other) {
      if (other == sentinel.world.Hazard.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getHazardType().isEmpty()) {
        hazardType_ = other.hazardType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSeverity().isEmpty()) {
        severity_ = other.severity_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getZoneId().isEmpty()) {
        zoneId_ = other.zoneId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (java.lang.Double.doubleToRawLongBits(other.getX()) != 0) {
        setX(other.getX());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getY()) != 0) {
        setY(other.getY());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getZ()) != 0) {
        setZ(other.getZ());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasDetectedAt()) {
        mergeDetectedAt(other.getDetectedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              hazardType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              severity_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              zoneId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              x_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              y_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              z_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 66: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetDetectedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object hazardType_ = "";
    /**
     * <code>string hazard_type = 2;</code>
     * @return The hazardType.
     */
    public java.lang.String getHazardType() {
      java.lang.Object ref = hazardType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hazardType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hazard_type = 2;</code>
     * @return The bytes for hazardType.
     */
    public com.google.protobuf.ByteString
        getHazardTypeBytes() {
      java.lang.Object ref = hazardType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hazardType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hazard_type = 2;</code>
     * @param value The hazardType to set.
     * @return This builder for chaining.
     */
    public Builder setHazardType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hazardType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string hazard_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHazardType() {
      hazardType_ = getDefaultInstance().getHazardType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string hazard_type = 2;</code>
     * @param value The bytes for hazardType to set.
     * @return This builder for chaining.
     */
    public Builder setHazardTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hazardType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object severity_ = "";
    /**
     * <code>string severity = 3;</code>
     * @return The severity.
     */
    public java.lang.String getSeverity() {
      java.lang.Object ref = severity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        severity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string severity = 3;</code>
     * @return The bytes for severity.
     */
    public com.google.protobuf.ByteString
        getSeverityBytes() {
      java.lang.Object ref = severity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        severity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string severity = 3;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      severity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      severity_ = getDefaultInstance().getSeverity();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string severity = 3;</code>
     * @param value The bytes for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      severity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object zoneId_ = "";
    /**
     * <code>string zone_id = 4;</code>
     * @return The zoneId.
     */
    public java.lang.String getZoneId() {
      java.lang.Object ref = zoneId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zoneId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string zone_id = 4;</code>
     * @return The bytes for zoneId.
     */
    public com.google.protobuf.ByteString
        getZoneIdBytes() {
      java.lang.Object ref = zoneId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string zone_id = 4;</code>
     * @param value The zoneId to set.
     * @return This builder for chaining.
     */
    public Builder setZoneId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      zoneId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string zone_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearZoneId() {
      zoneId_ = getDefaultInstance().getZoneId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string zone_id = 4;</code>
     * @param value The bytes for zoneId to set.
     * @return This builder for chaining.
     */
    public Builder setZoneIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      zoneId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private double x_ ;
    /**
     * <code>double x = 5;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }
    /**
     * <code>double x = 5;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(double value) {

      x_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double x = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000010);
      x_ = 0D;
      onChanged();
      return this;
    }

    private double y_ ;
    /**
     * <code>double y = 6;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }
    /**
     * <code>double y = 6;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(double value) {

      y_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double y = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000020);
      y_ = 0D;
      onChanged();
      return this;
    }

    private double z_ ;
    /**
     * <code>double z = 7;</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }
    /**
     * <code>double z = 7;</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(double value) {

      z_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double z = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000040);
      z_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 8;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 8;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 8;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private sentinel.common.Timestamp detectedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> detectedAtBuilder_;
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     * @return Whether the detectedAt field is set.
     */
    public boolean hasDetectedAt() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     * @return The detectedAt.
     */
    public sentinel.common.Timestamp getDetectedAt() {
      if (detectedAtBuilder_ == null) {
        return detectedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : detectedAt_;
      } else {
        return detectedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public Builder setDetectedAt(sentinel.common.Timestamp value) {
      if (detectedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        detectedAt_ = value;
      } else {
        detectedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public Builder setDetectedAt(
        sentinel.common.Timestamp.Builder builderForValue) {
      if (detectedAtBuilder_ == null) {
        detectedAt_ = builderForValue.build();
      } else {
        detectedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public Builder mergeDetectedAt(sentinel.common.Timestamp value) {
      if (detectedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          detectedAt_ != null &&
          detectedAt_ != sentinel.common.Timestamp.getDefaultInstance()) {
          getDetectedAtBuilder().mergeFrom(value);
        } else {
          detectedAt_ = value;
        }
      } else {
        detectedAtBuilder_.mergeFrom(value);
      }
      if (detectedAt_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public Builder clearDetectedAt() {
      bitField0_ = (bitField0_ & ~0x00000100);
      detectedAt_ = null;
      if (detectedAtBuilder_ != null) {
        detectedAtBuilder_.dispose();
        detectedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public sentinel.common.Timestamp.Builder getDetectedAtBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetDetectedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    public sentinel.common.TimestampOrBuilder getDetectedAtOrBuilder() {
      if (detectedAtBuilder_ != null) {
        return detectedAtBuilder_.getMessageOrBuilder();
      } else {
        return detectedAt_ == null ?
            sentinel.common.Timestamp.getDefaultInstance() : detectedAt_;
      }
    }
    /**
     * <code>.sentinel.common.Timestamp detected_at = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> 
        internalGetDetectedAtFieldBuilder() {
      if (detectedAtBuilder_ == null) {
        detectedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder>(
                getDetectedAt(),
                getParentForChildren(),
                isClean());
        detectedAt_ = null;
      }
      return detectedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.world.Hazard)
  }

  // @@protoc_insertion_point(class_scope:sentinel.world.Hazard)
  private static final sentinel.world.Hazard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.world.Hazard();
  }

  public static sentinel.world.Hazard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Hazard>
      PARSER = new com.google.protobuf.AbstractParser<Hazard>() {
    @java.lang.Override
    public Hazard parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Hazard> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Hazard> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.world.Hazard getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

