// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: world.proto
// Protobuf Java Version: 4.34.1

package sentinel.world;

/**
 * Protobuf type {@code sentinel.world.StreamSnapshotsRequest}
 */
@com.google.protobuf.Generated
public final class StreamSnapshotsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.world.StreamSnapshotsRequest)
    StreamSnapshotsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "StreamSnapshotsRequest");
  }
  // Use StreamSnapshotsRequest.newBuilder() to construct.
  private StreamSnapshotsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamSnapshotsRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.world.StreamSnapshotsRequest.class, sentinel.world.StreamSnapshotsRequest.Builder.class);
  }

  public static final int INTERVAL_MS_FIELD_NUMBER = 1;
  private int intervalMs_ = 0;
  /**
   * <code>int32 interval_ms = 1;</code>
   * @return The intervalMs.
   */
  @java.lang.Override
  public int getIntervalMs() {
    return intervalMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (intervalMs_ != 0) {
      output.writeInt32(1, intervalMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (intervalMs_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, intervalMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.world.StreamSnapshotsRequest)) {
      return super.equals(obj);
    }
    sentinel.world.StreamSnapshotsRequest other = (sentinel.world.StreamSnapshotsRequest) obj;

    if (getIntervalMs()
        != other.getIntervalMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INTERVAL_MS_FIELD_NUMBER;
    hash = (53 * hash) + getIntervalMs();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.world.StreamSnapshotsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.world.StreamSnapshotsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.world.StreamSnapshotsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.world.StreamSnapshotsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.world.StreamSnapshotsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.world.StreamSnapshotsRequest)
      sentinel.world.StreamSnapshotsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.world.StreamSnapshotsRequest.class, sentinel.world.StreamSnapshotsRequest.Builder.class);
    }

    // Construct using sentinel.world.StreamSnapshotsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      intervalMs_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.world.World.internal_static_sentinel_world_StreamSnapshotsRequest_descriptor;
    }

    @java.lang.Override
    public sentinel.world.StreamSnapshotsRequest getDefaultInstanceForType() {
      return sentinel.world.StreamSnapshotsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.world.StreamSnapshotsRequest build() {
      sentinel.world.StreamSnapshotsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.world.StreamSnapshotsRequest buildPartial() {
      sentinel.world.StreamSnapshotsRequest result = new sentinel.world.StreamSnapshotsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.world.StreamSnapshotsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.intervalMs_ = intervalMs_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.world.StreamSnapshotsRequest) {
        return mergeFrom((sentinel.world.StreamSnapshotsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.world.StreamSnapshotsRequest other) {
      if (other == sentinel.world.StreamSnapshotsRequest.getDefaultInstance()) return this;
      if (other.getIntervalMs() != 0) {
        setIntervalMs(other.getIntervalMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              intervalMs_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int intervalMs_ ;
    /**
     * <code>int32 interval_ms = 1;</code>
     * @return The intervalMs.
     */
    @java.lang.Override
    public int getIntervalMs() {
      return intervalMs_;
    }
    /**
     * <code>int32 interval_ms = 1;</code>
     * @param value The intervalMs to set.
     * @return This builder for chaining.
     */
    public Builder setIntervalMs(int value) {

      intervalMs_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 interval_ms = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntervalMs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      intervalMs_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.world.StreamSnapshotsRequest)
  }

  // @@protoc_insertion_point(class_scope:sentinel.world.StreamSnapshotsRequest)
  private static final sentinel.world.StreamSnapshotsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.world.StreamSnapshotsRequest();
  }

  public static sentinel.world.StreamSnapshotsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamSnapshotsRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamSnapshotsRequest>() {
    @java.lang.Override
    public StreamSnapshotsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamSnapshotsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamSnapshotsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.world.StreamSnapshotsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

