// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: world.proto
// Protobuf Java Version: 4.34.1

package sentinel.world;

@com.google.protobuf.Generated
public final class World extends com.google.protobuf.GeneratedFile {
  private World() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "World");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Plant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Plant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Building_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Building_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Zone_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Zone_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Worker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Worker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Sensor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Sensor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_Hazard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_Hazard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_WorldSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_WorldSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_WeatherState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_WeatherState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_GetSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_GetSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_GetSnapshotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_GetSnapshotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_StreamSnapshotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_StreamSnapshotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_StreamSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_StreamSnapshotsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_ListSnapshotsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_ListSnapshotsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sentinel_world_ListSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sentinel_world_ListSnapshotsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013world.proto\022\016sentinel.world\032\014common.pr" +
      "oto\"\216\001\n\005Plant\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022" +
      "\016\n\006status\030\003 \001(\t\022+\n\tbuildings\030\004 \003(\0132\030.sen" +
      "tinel.world.Building\022.\n\nupdated_at\030\005 \001(\013" +
      "2\032.sentinel.common.Timestamp\"I\n\010Building" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022#\n\005zones\030\003 \003(" +
      "\0132\024.sentinel.world.Zone\"\226\001\n\004Zone\022\n\n\002id\030\001" +
      " \001(\t\022\014\n\004name\030\002 \001(\t\022\021\n\tzone_type\030\003 \001(\t\022\t\n" +
      "\001x\030\004 \001(\001\022\t\n\001y\030\005 \001(\001\022\t\n\001z\030\006 \001(\001\022\r\n\005width\030" +
      "\007 \001(\005\022\r\n\005depth\030\010 \001(\005\022\016\n\006height\030\t \001(\005\022\022\n\n" +
      "risk_score\030\n \001(\001\"\254\001\n\006Worker\022\n\n\002id\030\001 \001(\t\022" +
      "\014\n\004name\030\002 \001(\t\022\014\n\004role\030\003 \001(\t\022\016\n\006status\030\004 " +
      "\001(\t\022\017\n\007zone_id\030\005 \001(\t\022\t\n\001x\030\006 \001(\001\022\t\n\001y\030\007 \001" +
      "(\001\022\t\n\001z\030\010 \001(\001\022\022\n\nhas_helmet\030\t \001(\010\022\020\n\010has" +
      "_vest\030\n \001(\010\022\022\n\nhas_gloves\030\013 \001(\010\"\244\001\n\006Sens" +
      "or\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013sensor_t" +
      "ype\030\003 \001(\t\022\017\n\007zone_id\030\004 \001(\t\022\r\n\005value\030\005 \001(" +
      "\001\022\014\n\004unit\030\006 \001(\t\022\016\n\006status\030\007 \001(\t\022\026\n\016thres" +
      "hold_high\030\010 \001(\001\022\025\n\rthreshold_low\030\t \001(\001\"\263" +
      "\001\n\006Hazard\022\n\n\002id\030\001 \001(\t\022\023\n\013hazard_type\030\002 \001" +
      "(\t\022\020\n\010severity\030\003 \001(\t\022\017\n\007zone_id\030\004 \001(\t\022\t\n" +
      "\001x\030\005 \001(\001\022\t\n\001y\030\006 \001(\001\022\t\n\001z\030\007 \001(\001\022\023\n\013descri" +
      "ption\030\010 \001(\t\022/\n\013detected_at\030\t \001(\0132\032.senti" +
      "nel.common.Timestamp\"\237\002\n\rWorldSnapshot\022\017" +
      "\n\007version\030\001 \001(\003\022-\n\ttimestamp\030\002 \001(\0132\032.sen" +
      "tinel.common.Timestamp\022$\n\005plant\030\003 \001(\0132\025." +
      "sentinel.world.Plant\022\'\n\007workers\030\004 \003(\0132\026." +
      "sentinel.world.Worker\022\'\n\007sensors\030\005 \003(\0132\026" +
      ".sentinel.world.Sensor\022\'\n\007hazards\030\006 \003(\0132" +
      "\026.sentinel.world.Hazard\022-\n\007weather\030\007 \001(\013" +
      "2\034.sentinel.world.WeatherState\"I\n\014Weathe" +
      "rState\022\023\n\013temperature\030\001 \001(\001\022\022\n\nwind_spee" +
      "d\030\002 \001(\001\022\020\n\010humidity\030\003 \001(\001\"%\n\022GetSnapshot" +
      "Request\022\017\n\007version\030\001 \001(\003\"F\n\023GetSnapshotR" +
      "esponse\022/\n\010snapshot\030\001 \001(\0132\035.sentinel.wor" +
      "ld.WorldSnapshot\"-\n\026StreamSnapshotsReque" +
      "st\022\023\n\013interval_ms\030\001 \001(\005\"J\n\027StreamSnapsho" +
      "tsResponse\022/\n\010snapshot\030\001 \001(\0132\035.sentinel." +
      "world.WorldSnapshot\"%\n\024ListSnapshotsRequ" +
      "est\022\r\n\005limit\030\001 \001(\005\"X\n\025ListSnapshotsRespo" +
      "nse\0220\n\tsnapshots\030\001 \003(\0132\035.sentinel.world." +
      "WorldSnapshot\022\r\n\005total\030\002 \001(\0052\252\002\n\014WorldSe" +
      "rvice\022V\n\013GetSnapshot\022\".sentinel.world.Ge" +
      "tSnapshotRequest\032#.sentinel.world.GetSna" +
      "pshotResponse\022d\n\017StreamSnapshots\022&.senti" +
      "nel.world.StreamSnapshotsRequest\032\'.senti" +
      "nel.world.StreamSnapshotsResponse0\001\022\\\n\rL" +
      "istSnapshots\022$.sentinel.world.ListSnapsh" +
      "otsRequest\032%.sentinel.world.ListSnapshot" +
      "sResponseBC\n\016sentinel.worldP\001Z/github.co" +
      "m/sentinel/services/go/pkg/proto/worldb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sentinel.common.Common.getDescriptor(),
        });
    internal_static_sentinel_world_Plant_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_sentinel_world_Plant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Plant_descriptor,
        new java.lang.String[] { "Id", "Name", "Status", "Buildings", "UpdatedAt", });
    internal_static_sentinel_world_Building_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_sentinel_world_Building_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Building_descriptor,
        new java.lang.String[] { "Id", "Name", "Zones", });
    internal_static_sentinel_world_Zone_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_sentinel_world_Zone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Zone_descriptor,
        new java.lang.String[] { "Id", "Name", "ZoneType", "X", "Y", "Z", "Width", "Depth", "Height", "RiskScore", });
    internal_static_sentinel_world_Worker_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_sentinel_world_Worker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Worker_descriptor,
        new java.lang.String[] { "Id", "Name", "Role", "Status", "ZoneId", "X", "Y", "Z", "HasHelmet", "HasVest", "HasGloves", });
    internal_static_sentinel_world_Sensor_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_sentinel_world_Sensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Sensor_descriptor,
        new java.lang.String[] { "Id", "Name", "SensorType", "ZoneId", "Value", "Unit", "Status", "ThresholdHigh", "ThresholdLow", });
    internal_static_sentinel_world_Hazard_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_sentinel_world_Hazard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_Hazard_descriptor,
        new java.lang.String[] { "Id", "HazardType", "Severity", "ZoneId", "X", "Y", "Z", "Description", "DetectedAt", });
    internal_static_sentinel_world_WorldSnapshot_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_sentinel_world_WorldSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_WorldSnapshot_descriptor,
        new java.lang.String[] { "Version", "Timestamp", "Plant", "Workers", "Sensors", "Hazards", "Weather", });
    internal_static_sentinel_world_WeatherState_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_sentinel_world_WeatherState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_WeatherState_descriptor,
        new java.lang.String[] { "Temperature", "WindSpeed", "Humidity", });
    internal_static_sentinel_world_GetSnapshotRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_sentinel_world_GetSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_GetSnapshotRequest_descriptor,
        new java.lang.String[] { "Version", });
    internal_static_sentinel_world_GetSnapshotResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_sentinel_world_GetSnapshotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_GetSnapshotResponse_descriptor,
        new java.lang.String[] { "Snapshot", });
    internal_static_sentinel_world_StreamSnapshotsRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_sentinel_world_StreamSnapshotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_StreamSnapshotsRequest_descriptor,
        new java.lang.String[] { "IntervalMs", });
    internal_static_sentinel_world_StreamSnapshotsResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_sentinel_world_StreamSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_StreamSnapshotsResponse_descriptor,
        new java.lang.String[] { "Snapshot", });
    internal_static_sentinel_world_ListSnapshotsRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_sentinel_world_ListSnapshotsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_ListSnapshotsRequest_descriptor,
        new java.lang.String[] { "Limit", });
    internal_static_sentinel_world_ListSnapshotsResponse_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_sentinel_world_ListSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sentinel_world_ListSnapshotsResponse_descriptor,
        new java.lang.String[] { "Snapshots", "Total", });
    descriptor.resolveAllFeaturesImmutable();
    sentinel.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
