// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: world.proto
// Protobuf Java Version: 4.34.1

package sentinel.world;

@com.google.protobuf.Generated
public interface ZoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.world.Zone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string zone_type = 3;</code>
   * @return The zoneType.
   */
  java.lang.String getZoneType();
  /**
   * <code>string zone_type = 3;</code>
   * @return The bytes for zoneType.
   */
  com.google.protobuf.ByteString
      getZoneTypeBytes();

  /**
   * <code>double x = 4;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 5;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 6;</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>int32 width = 7;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 depth = 8;</code>
   * @return The depth.
   */
  int getDepth();

  /**
   * <code>int32 height = 9;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>double risk_score = 10;</code>
   * @return The riskScore.
   */
  double getRiskScore();
}
