// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface CheckComplianceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.CheckComplianceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string plant_id = 1;</code>
   * @return The plantId.
   */
  java.lang.String getPlantId();
  /**
   * <code>string plant_id = 1;</code>
   * @return The bytes for plantId.
   */
  com.google.protobuf.ByteString
      getPlantIdBytes();

  /**
   * <code>string zone_id = 2;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zone_id = 2;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>string worker_id = 3;</code>
   * @return The workerId.
   */
  java.lang.String getWorkerId();
  /**
   * <code>string worker_id = 3;</code>
   * @return The bytes for workerId.
   */
  com.google.protobuf.ByteString
      getWorkerIdBytes();
}
