// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface ComplianceViolationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.ComplianceViolation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rule_id = 1;</code>
   * @return The ruleId.
   */
  java.lang.String getRuleId();
  /**
   * <code>string rule_id = 1;</code>
   * @return The bytes for ruleId.
   */
  com.google.protobuf.ByteString
      getRuleIdBytes();

  /**
   * <code>string rule_name = 2;</code>
   * @return The ruleName.
   */
  java.lang.String getRuleName();
  /**
   * <code>string rule_name = 2;</code>
   * @return The bytes for ruleName.
   */
  com.google.protobuf.ByteString
      getRuleNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string severity = 4;</code>
   * @return The severity.
   */
  java.lang.String getSeverity();
  /**
   * <code>string severity = 4;</code>
   * @return The bytes for severity.
   */
  com.google.protobuf.ByteString
      getSeverityBytes();

  /**
   * <code>string entity_id = 5;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 5;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>string entity_type = 6;</code>
   * @return The entityType.
   */
  java.lang.String getEntityType();
  /**
   * <code>string entity_type = 6;</code>
   * @return The bytes for entityType.
   */
  com.google.protobuf.ByteString
      getEntityTypeBytes();

  /**
   * <code>string regulation = 7;</code>
   * @return The regulation.
   */
  java.lang.String getRegulation();
  /**
   * <code>string regulation = 7;</code>
   * @return The bytes for regulation.
   */
  com.google.protobuf.ByteString
      getRegulationBytes();
}
