// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface DetectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.Detection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string object_class = 1;</code>
   * @return The objectClass.
   */
  java.lang.String getObjectClass();
  /**
   * <code>string object_class = 1;</code>
   * @return The bytes for objectClass.
   */
  com.google.protobuf.ByteString
      getObjectClassBytes();

  /**
   * <code>double confidence = 2;</code>
   * @return The confidence.
   */
  double getConfidence();

  /**
   * <code>double x = 3;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 4;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double width = 5;</code>
   * @return The width.
   */
  double getWidth();

  /**
   * <code>double height = 6;</code>
   * @return The height.
   */
  double getHeight();

  /**
   * <code>string track_id = 7;</code>
   * @return The trackId.
   */
  java.lang.String getTrackId();
  /**
   * <code>string track_id = 7;</code>
   * @return The bytes for trackId.
   */
  com.google.protobuf.ByteString
      getTrackIdBytes();
}
