// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface InferVisionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.InferVisionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes image_data = 1;</code>
   * @return The imageData.
   */
  com.google.protobuf.ByteString getImageData();

  /**
   * <code>string camera_id = 2;</code>
   * @return The cameraId.
   */
  java.lang.String getCameraId();
  /**
   * <code>string camera_id = 2;</code>
   * @return The bytes for cameraId.
   */
  com.google.protobuf.ByteString
      getCameraIdBytes();
}
