// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

/**
 * Protobuf type {@code sentinel.intelligence.PredictRequest}
 */
@com.google.protobuf.Generated
public final class PredictRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.intelligence.PredictRequest)
    PredictRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PredictRequest");
  }
  // Use PredictRequest.newBuilder() to construct.
  private PredictRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictRequest() {
    plantId_ = "";
    sensorIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.intelligence.PredictRequest.class, sentinel.intelligence.PredictRequest.Builder.class);
  }

  public static final int PLANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object plantId_ = "";
  /**
   * <code>string plant_id = 1;</code>
   * @return The plantId.
   */
  @java.lang.Override
  public java.lang.String getPlantId() {
    java.lang.Object ref = plantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plantId_ = s;
      return s;
    }
  }
  /**
   * <code>string plant_id = 1;</code>
   * @return The bytes for plantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlantIdBytes() {
    java.lang.Object ref = plantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HORIZON_MINUTES_FIELD_NUMBER = 2;
  private int horizonMinutes_ = 0;
  /**
   * <code>int32 horizon_minutes = 2;</code>
   * @return The horizonMinutes.
   */
  @java.lang.Override
  public int getHorizonMinutes() {
    return horizonMinutes_;
  }

  public static final int SENSOR_IDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList sensorIds_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @return A list containing the sensorIds.
   */
  public com.google.protobuf.ProtocolStringList
      getSensorIdsList() {
    return sensorIds_;
  }
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @return The count of sensorIds.
   */
  public int getSensorIdsCount() {
    return sensorIds_.size();
  }
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The sensorIds at the given index.
   */
  public java.lang.String getSensorIds(int index) {
    return sensorIds_.get(index);
  }
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sensorIds at the given index.
   */
  public com.google.protobuf.ByteString
      getSensorIdsBytes(int index) {
    return sensorIds_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, plantId_);
    }
    if (horizonMinutes_ != 0) {
      output.writeInt32(2, horizonMinutes_);
    }
    for (int i = 0; i < sensorIds_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, sensorIds_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(plantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, plantId_);
    }
    if (horizonMinutes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, horizonMinutes_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < sensorIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(sensorIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSensorIdsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.intelligence.PredictRequest)) {
      return super.equals(obj);
    }
    sentinel.intelligence.PredictRequest other = (sentinel.intelligence.PredictRequest) obj;

    if (!getPlantId()
        .equals(other.getPlantId())) return false;
    if (getHorizonMinutes()
        != other.getHorizonMinutes()) return false;
    if (!getSensorIdsList()
        .equals(other.getSensorIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPlantId().hashCode();
    hash = (37 * hash) + HORIZON_MINUTES_FIELD_NUMBER;
    hash = (53 * hash) + getHorizonMinutes();
    if (getSensorIdsCount() > 0) {
      hash = (37 * hash) + SENSOR_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getSensorIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.intelligence.PredictRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.intelligence.PredictRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.intelligence.PredictRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.intelligence.PredictRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.intelligence.PredictRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.intelligence.PredictRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.intelligence.PredictRequest)
      sentinel.intelligence.PredictRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.intelligence.PredictRequest.class, sentinel.intelligence.PredictRequest.Builder.class);
    }

    // Construct using sentinel.intelligence.PredictRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      plantId_ = "";
      horizonMinutes_ = 0;
      sensorIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictRequest_descriptor;
    }

    @java.lang.Override
    public sentinel.intelligence.PredictRequest getDefaultInstanceForType() {
      return sentinel.intelligence.PredictRequest.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.intelligence.PredictRequest build() {
      sentinel.intelligence.PredictRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.intelligence.PredictRequest buildPartial() {
      sentinel.intelligence.PredictRequest result = new sentinel.intelligence.PredictRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.intelligence.PredictRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.plantId_ = plantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.horizonMinutes_ = horizonMinutes_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        sensorIds_.makeImmutable();
        result.sensorIds_ = sensorIds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.intelligence.PredictRequest) {
        return mergeFrom((sentinel.intelligence.PredictRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.intelligence.PredictRequest other) {
      if (other == sentinel.intelligence.PredictRequest.getDefaultInstance()) return this;
      if (!other.getPlantId().isEmpty()) {
        plantId_ = other.plantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getHorizonMinutes() != 0) {
        setHorizonMinutes(other.getHorizonMinutes());
      }
      if (!other.sensorIds_.isEmpty()) {
        if (sensorIds_.isEmpty()) {
          sensorIds_ = other.sensorIds_;
          bitField0_ |= 0x00000004;
        } else {
          ensureSensorIdsIsMutable();
          sensorIds_.addAll(other.sensorIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              plantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              horizonMinutes_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              ensureSensorIdsIsMutable();
              sensorIds_.add(input.readStringRequireUtf8());
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object plantId_ = "";
    /**
     * <code>string plant_id = 1;</code>
     * @return The plantId.
     */
    public java.lang.String getPlantId() {
      java.lang.Object ref = plantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plant_id = 1;</code>
     * @return The bytes for plantId.
     */
    public com.google.protobuf.ByteString
        getPlantIdBytes() {
      java.lang.Object ref = plantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plant_id = 1;</code>
     * @param value The plantId to set.
     * @return This builder for chaining.
     */
    public Builder setPlantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      plantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string plant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlantId() {
      plantId_ = getDefaultInstance().getPlantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string plant_id = 1;</code>
     * @param value The bytes for plantId to set.
     * @return This builder for chaining.
     */
    public Builder setPlantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      plantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int horizonMinutes_ ;
    /**
     * <code>int32 horizon_minutes = 2;</code>
     * @return The horizonMinutes.
     */
    @java.lang.Override
    public int getHorizonMinutes() {
      return horizonMinutes_;
    }
    /**
     * <code>int32 horizon_minutes = 2;</code>
     * @param value The horizonMinutes to set.
     * @return This builder for chaining.
     */
    public Builder setHorizonMinutes(int value) {

      horizonMinutes_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 horizon_minutes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHorizonMinutes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      horizonMinutes_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList sensorIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSensorIdsIsMutable() {
      if (!sensorIds_.isModifiable()) {
        sensorIds_ = new com.google.protobuf.LazyStringArrayList(sensorIds_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @return A list containing the sensorIds.
     */
    public com.google.protobuf.ProtocolStringList
        getSensorIdsList() {
      sensorIds_.makeImmutable();
      return sensorIds_;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @return The count of sensorIds.
     */
    public int getSensorIdsCount() {
      return sensorIds_.size();
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The sensorIds at the given index.
     */
    public java.lang.String getSensorIds(int index) {
      return sensorIds_.get(index);
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the sensorIds at the given index.
     */
    public com.google.protobuf.ByteString
        getSensorIdsBytes(int index) {
      return sensorIds_.getByteString(index);
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The sensorIds to set.
     * @return This builder for chaining.
     */
    public Builder setSensorIds(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSensorIdsIsMutable();
      sensorIds_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param value The sensorIds to add.
     * @return This builder for chaining.
     */
    public Builder addSensorIds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSensorIdsIsMutable();
      sensorIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param values The sensorIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllSensorIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureSensorIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sensorIds_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorIds() {
      sensorIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string sensor_ids = 3;</code>
     * @param value The bytes of the sensorIds to add.
     * @return This builder for chaining.
     */
    public Builder addSensorIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSensorIdsIsMutable();
      sensorIds_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.intelligence.PredictRequest)
  }

  // @@protoc_insertion_point(class_scope:sentinel.intelligence.PredictRequest)
  private static final sentinel.intelligence.PredictRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.intelligence.PredictRequest();
  }

  public static sentinel.intelligence.PredictRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictRequest>
      PARSER = new com.google.protobuf.AbstractParser<PredictRequest>() {
    @java.lang.Override
    public PredictRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.intelligence.PredictRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

