// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

/**
 * Protobuf type {@code sentinel.intelligence.PredictResponse}
 */
@com.google.protobuf.Generated
public final class PredictResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.intelligence.PredictResponse)
    PredictResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "PredictResponse");
  }
  // Use PredictResponse.newBuilder() to construct.
  private PredictResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PredictResponse() {
    predictions_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.intelligence.PredictResponse.class, sentinel.intelligence.PredictResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PREDICTIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<sentinel.intelligence.Prediction> predictions_;
  /**
   * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<sentinel.intelligence.Prediction> getPredictionsList() {
    return predictions_;
  }
  /**
   * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends sentinel.intelligence.PredictionOrBuilder> 
      getPredictionsOrBuilderList() {
    return predictions_;
  }
  /**
   * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
   */
  @java.lang.Override
  public int getPredictionsCount() {
    return predictions_.size();
  }
  /**
   * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
   */
  @java.lang.Override
  public sentinel.intelligence.Prediction getPredictions(int index) {
    return predictions_.get(index);
  }
  /**
   * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
   */
  @java.lang.Override
  public sentinel.intelligence.PredictionOrBuilder getPredictionsOrBuilder(
      int index) {
    return predictions_.get(index);
  }

  public static final int GENERATED_AT_FIELD_NUMBER = 2;
  private sentinel.common.Timestamp generatedAt_;
  /**
   * <code>.sentinel.common.Timestamp generated_at = 2;</code>
   * @return Whether the generatedAt field is set.
   */
  @java.lang.Override
  public boolean hasGeneratedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.common.Timestamp generated_at = 2;</code>
   * @return The generatedAt.
   */
  @java.lang.Override
  public sentinel.common.Timestamp getGeneratedAt() {
    return generatedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : generatedAt_;
  }
  /**
   * <code>.sentinel.common.Timestamp generated_at = 2;</code>
   */
  @java.lang.Override
  public sentinel.common.TimestampOrBuilder getGeneratedAtOrBuilder() {
    return generatedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : generatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < predictions_.size(); i++) {
      output.writeMessage(1, predictions_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getGeneratedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = predictions_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(predictions_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getGeneratedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.intelligence.PredictResponse)) {
      return super.equals(obj);
    }
    sentinel.intelligence.PredictResponse other = (sentinel.intelligence.PredictResponse) obj;

    if (!getPredictionsList()
        .equals(other.getPredictionsList())) return false;
    if (hasGeneratedAt() != other.hasGeneratedAt()) return false;
    if (hasGeneratedAt()) {
      if (!getGeneratedAt()
          .equals(other.getGeneratedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPredictionsCount() > 0) {
      hash = (37 * hash) + PREDICTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPredictionsList().hashCode();
    }
    if (hasGeneratedAt()) {
      hash = (37 * hash) + GENERATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getGeneratedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.intelligence.PredictResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.intelligence.PredictResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.intelligence.PredictResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.intelligence.PredictResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.intelligence.PredictResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.intelligence.PredictResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.intelligence.PredictResponse)
      sentinel.intelligence.PredictResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.intelligence.PredictResponse.class, sentinel.intelligence.PredictResponse.Builder.class);
    }

    // Construct using sentinel.intelligence.PredictResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPredictionsFieldBuilder();
        internalGetGeneratedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (predictionsBuilder_ == null) {
        predictions_ = java.util.Collections.emptyList();
      } else {
        predictions_ = null;
        predictionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      generatedAt_ = null;
      if (generatedAtBuilder_ != null) {
        generatedAtBuilder_.dispose();
        generatedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.intelligence.Intelligence.internal_static_sentinel_intelligence_PredictResponse_descriptor;
    }

    @java.lang.Override
    public sentinel.intelligence.PredictResponse getDefaultInstanceForType() {
      return sentinel.intelligence.PredictResponse.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.intelligence.PredictResponse build() {
      sentinel.intelligence.PredictResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.intelligence.PredictResponse buildPartial() {
      sentinel.intelligence.PredictResponse result = new sentinel.intelligence.PredictResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(sentinel.intelligence.PredictResponse result) {
      if (predictionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          predictions_ = java.util.Collections.unmodifiableList(predictions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.predictions_ = predictions_;
      } else {
        result.predictions_ = predictionsBuilder_.build();
      }
    }

    private void buildPartial0(sentinel.intelligence.PredictResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.generatedAt_ = generatedAtBuilder_ == null
            ? generatedAt_
            : generatedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.intelligence.PredictResponse) {
        return mergeFrom((sentinel.intelligence.PredictResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.intelligence.PredictResponse other) {
      if (other == sentinel.intelligence.PredictResponse.getDefaultInstance()) return this;
      if (predictionsBuilder_ == null) {
        if (!other.predictions_.isEmpty()) {
          if (predictions_.isEmpty()) {
            predictions_ = other.predictions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePredictionsIsMutable();
            predictions_.addAll(other.predictions_);
          }
          onChanged();
        }
      } else {
        if (!other.predictions_.isEmpty()) {
          if (predictionsBuilder_.isEmpty()) {
            predictionsBuilder_.dispose();
            predictionsBuilder_ = null;
            predictions_ = other.predictions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            predictionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPredictionsFieldBuilder() : null;
          } else {
            predictionsBuilder_.addAllMessages(other.predictions_);
          }
        }
      }
      if (other.hasGeneratedAt()) {
        mergeGeneratedAt(other.getGeneratedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sentinel.intelligence.Prediction m =
                  input.readMessage(
                      sentinel.intelligence.Prediction.parser(),
                      extensionRegistry);
              if (predictionsBuilder_ == null) {
                ensurePredictionsIsMutable();
                predictions_.add(m);
              } else {
                predictionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetGeneratedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<sentinel.intelligence.Prediction> predictions_ =
      java.util.Collections.emptyList();
    private void ensurePredictionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        predictions_ = new java.util.ArrayList<sentinel.intelligence.Prediction>(predictions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        sentinel.intelligence.Prediction, sentinel.intelligence.Prediction.Builder, sentinel.intelligence.PredictionOrBuilder> predictionsBuilder_;

    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public java.util.List<sentinel.intelligence.Prediction> getPredictionsList() {
      if (predictionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(predictions_);
      } else {
        return predictionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public int getPredictionsCount() {
      if (predictionsBuilder_ == null) {
        return predictions_.size();
      } else {
        return predictionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public sentinel.intelligence.Prediction getPredictions(int index) {
      if (predictionsBuilder_ == null) {
        return predictions_.get(index);
      } else {
        return predictionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder setPredictions(
        int index, sentinel.intelligence.Prediction value) {
      if (predictionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionsIsMutable();
        predictions_.set(index, value);
        onChanged();
      } else {
        predictionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder setPredictions(
        int index, sentinel.intelligence.Prediction.Builder builderForValue) {
      if (predictionsBuilder_ == null) {
        ensurePredictionsIsMutable();
        predictions_.set(index, builderForValue.build());
        onChanged();
      } else {
        predictionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder addPredictions(sentinel.intelligence.Prediction value) {
      if (predictionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionsIsMutable();
        predictions_.add(value);
        onChanged();
      } else {
        predictionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder addPredictions(
        int index, sentinel.intelligence.Prediction value) {
      if (predictionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionsIsMutable();
        predictions_.add(index, value);
        onChanged();
      } else {
        predictionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder addPredictions(
        sentinel.intelligence.Prediction.Builder builderForValue) {
      if (predictionsBuilder_ == null) {
        ensurePredictionsIsMutable();
        predictions_.add(builderForValue.build());
        onChanged();
      } else {
        predictionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder addPredictions(
        int index, sentinel.intelligence.Prediction.Builder builderForValue) {
      if (predictionsBuilder_ == null) {
        ensurePredictionsIsMutable();
        predictions_.add(index, builderForValue.build());
        onChanged();
      } else {
        predictionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder addAllPredictions(
        java.lang.Iterable<? extends sentinel.intelligence.Prediction> values) {
      if (predictionsBuilder_ == null) {
        ensurePredictionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, predictions_);
        onChanged();
      } else {
        predictionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder clearPredictions() {
      if (predictionsBuilder_ == null) {
        predictions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        predictionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public Builder removePredictions(int index) {
      if (predictionsBuilder_ == null) {
        ensurePredictionsIsMutable();
        predictions_.remove(index);
        onChanged();
      } else {
        predictionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public sentinel.intelligence.Prediction.Builder getPredictionsBuilder(
        int index) {
      return internalGetPredictionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public sentinel.intelligence.PredictionOrBuilder getPredictionsOrBuilder(
        int index) {
      if (predictionsBuilder_ == null) {
        return predictions_.get(index);  } else {
        return predictionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public java.util.List<? extends sentinel.intelligence.PredictionOrBuilder> 
         getPredictionsOrBuilderList() {
      if (predictionsBuilder_ != null) {
        return predictionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(predictions_);
      }
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public sentinel.intelligence.Prediction.Builder addPredictionsBuilder() {
      return internalGetPredictionsFieldBuilder().addBuilder(
          sentinel.intelligence.Prediction.getDefaultInstance());
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public sentinel.intelligence.Prediction.Builder addPredictionsBuilder(
        int index) {
      return internalGetPredictionsFieldBuilder().addBuilder(
          index, sentinel.intelligence.Prediction.getDefaultInstance());
    }
    /**
     * <code>repeated .sentinel.intelligence.Prediction predictions = 1;</code>
     */
    public java.util.List<sentinel.intelligence.Prediction.Builder> 
         getPredictionsBuilderList() {
      return internalGetPredictionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        sentinel.intelligence.Prediction, sentinel.intelligence.Prediction.Builder, sentinel.intelligence.PredictionOrBuilder> 
        internalGetPredictionsFieldBuilder() {
      if (predictionsBuilder_ == null) {
        predictionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            sentinel.intelligence.Prediction, sentinel.intelligence.Prediction.Builder, sentinel.intelligence.PredictionOrBuilder>(
                predictions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        predictions_ = null;
      }
      return predictionsBuilder_;
    }

    private sentinel.common.Timestamp generatedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> generatedAtBuilder_;
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     * @return Whether the generatedAt field is set.
     */
    public boolean hasGeneratedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     * @return The generatedAt.
     */
    public sentinel.common.Timestamp getGeneratedAt() {
      if (generatedAtBuilder_ == null) {
        return generatedAt_ == null ? sentinel.common.Timestamp.getDefaultInstance() : generatedAt_;
      } else {
        return generatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public Builder setGeneratedAt(sentinel.common.Timestamp value) {
      if (generatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        generatedAt_ = value;
      } else {
        generatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public Builder setGeneratedAt(
        sentinel.common.Timestamp.Builder builderForValue) {
      if (generatedAtBuilder_ == null) {
        generatedAt_ = builderForValue.build();
      } else {
        generatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public Builder mergeGeneratedAt(sentinel.common.Timestamp value) {
      if (generatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          generatedAt_ != null &&
          generatedAt_ != sentinel.common.Timestamp.getDefaultInstance()) {
          getGeneratedAtBuilder().mergeFrom(value);
        } else {
          generatedAt_ = value;
        }
      } else {
        generatedAtBuilder_.mergeFrom(value);
      }
      if (generatedAt_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public Builder clearGeneratedAt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      generatedAt_ = null;
      if (generatedAtBuilder_ != null) {
        generatedAtBuilder_.dispose();
        generatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public sentinel.common.Timestamp.Builder getGeneratedAtBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetGeneratedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    public sentinel.common.TimestampOrBuilder getGeneratedAtOrBuilder() {
      if (generatedAtBuilder_ != null) {
        return generatedAtBuilder_.getMessageOrBuilder();
      } else {
        return generatedAt_ == null ?
            sentinel.common.Timestamp.getDefaultInstance() : generatedAt_;
      }
    }
    /**
     * <code>.sentinel.common.Timestamp generated_at = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder> 
        internalGetGeneratedAtFieldBuilder() {
      if (generatedAtBuilder_ == null) {
        generatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.common.Timestamp, sentinel.common.Timestamp.Builder, sentinel.common.TimestampOrBuilder>(
                getGeneratedAt(),
                getParentForChildren(),
                isClean());
        generatedAt_ = null;
      }
      return generatedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.intelligence.PredictResponse)
  }

  // @@protoc_insertion_point(class_scope:sentinel.intelligence.PredictResponse)
  private static final sentinel.intelligence.PredictResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.intelligence.PredictResponse();
  }

  public static sentinel.intelligence.PredictResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictResponse>
      PARSER = new com.google.protobuf.AbstractParser<PredictResponse>() {
    @java.lang.Override
    public PredictResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PredictResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.intelligence.PredictResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

