// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface PredictRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.PredictRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string plant_id = 1;</code>
   * @return The plantId.
   */
  java.lang.String getPlantId();
  /**
   * <code>string plant_id = 1;</code>
   * @return The bytes for plantId.
   */
  com.google.protobuf.ByteString
      getPlantIdBytes();

  /**
   * <code>int32 horizon_minutes = 2;</code>
   * @return The horizonMinutes.
   */
  int getHorizonMinutes();

  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @return A list containing the sensorIds.
   */
  java.util.List<java.lang.String>
      getSensorIdsList();
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @return The count of sensorIds.
   */
  int getSensorIdsCount();
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The sensorIds at the given index.
   */
  java.lang.String getSensorIds(int index);
  /**
   * <code>repeated string sensor_ids = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sensorIds at the given index.
   */
  com.google.protobuf.ByteString
      getSensorIdsBytes(int index);
}
