// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: intelligence.proto
// Protobuf Java Version: 4.34.1

package sentinel.intelligence;

@com.google.protobuf.Generated
public interface PredictionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.intelligence.Prediction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entity_id = 1;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 1;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>string entity_type = 2;</code>
   * @return The entityType.
   */
  java.lang.String getEntityType();
  /**
   * <code>string entity_type = 2;</code>
   * @return The bytes for entityType.
   */
  com.google.protobuf.ByteString
      getEntityTypeBytes();

  /**
   * <code>repeated double values = 3;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.Double> getValuesList();
  /**
   * <code>repeated double values = 3;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <code>repeated double values = 3;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  double getValues(int index);

  /**
   * <code>repeated .sentinel.common.Timestamp timestamps = 4;</code>
   */
  java.util.List<sentinel.common.Timestamp> 
      getTimestampsList();
  /**
   * <code>repeated .sentinel.common.Timestamp timestamps = 4;</code>
   */
  sentinel.common.Timestamp getTimestamps(int index);
  /**
   * <code>repeated .sentinel.common.Timestamp timestamps = 4;</code>
   */
  int getTimestampsCount();
  /**
   * <code>repeated .sentinel.common.Timestamp timestamps = 4;</code>
   */
  java.util.List<? extends sentinel.common.TimestampOrBuilder> 
      getTimestampsOrBuilderList();
  /**
   * <code>repeated .sentinel.common.Timestamp timestamps = 4;</code>
   */
  sentinel.common.TimestampOrBuilder getTimestampsOrBuilder(
      int index);

  /**
   * <code>double confidence = 5;</code>
   * @return The confidence.
   */
  double getConfidence();

  /**
   * <code>string scenario = 6;</code>
   * @return The scenario.
   */
  java.lang.String getScenario();
  /**
   * <code>string scenario = 6;</code>
   * @return The bytes for scenario.
   */
  com.google.protobuf.ByteString
      getScenarioBytes();
}
