// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker.proto
// Protobuf Java Version: 4.34.1

package sentinel.worker;

@com.google.protobuf.Generated
public interface GetWorkerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.worker.GetWorkerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   * @return Whether the worker field is set.
   */
  boolean hasWorker();
  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   * @return The worker.
   */
  sentinel.worker.Worker getWorker();
  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   */
  sentinel.worker.WorkerOrBuilder getWorkerOrBuilder();
}
