// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker.proto
// Protobuf Java Version: 4.34.1

package sentinel.worker;

@com.google.protobuf.Generated
public interface UpdateWorkerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sentinel.worker.UpdateWorkerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string role = 3;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 3;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string department = 5;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 5;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>string shift = 6;</code>
   * @return The shift.
   */
  java.lang.String getShift();
  /**
   * <code>string shift = 6;</code>
   * @return The bytes for shift.
   */
  com.google.protobuf.ByteString
      getShiftBytes();

  /**
   * <code>string zone_id = 7;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zone_id = 7;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>double x = 8;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 9;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 10;</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>repeated string current_ppe = 11;</code>
   * @return A list containing the currentPpe.
   */
  java.util.List<java.lang.String>
      getCurrentPpeList();
  /**
   * <code>repeated string current_ppe = 11;</code>
   * @return The count of currentPpe.
   */
  int getCurrentPpeCount();
  /**
   * <code>repeated string current_ppe = 11;</code>
   * @param index The index of the element to return.
   * @return The currentPpe at the given index.
   */
  java.lang.String getCurrentPpe(int index);
  /**
   * <code>repeated string current_ppe = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the currentPpe at the given index.
   */
  com.google.protobuf.ByteString
      getCurrentPpeBytes(int index);
}
