// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker.proto
// Protobuf Java Version: 4.34.1

package sentinel.worker;

/**
 * Protobuf type {@code sentinel.worker.WorkerUpdate}
 */
@com.google.protobuf.Generated
public final class WorkerUpdate extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:sentinel.worker.WorkerUpdate)
    WorkerUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "WorkerUpdate");
  }
  // Use WorkerUpdate.newBuilder() to construct.
  private WorkerUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private WorkerUpdate() {
    updateType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            sentinel.worker.WorkerUpdate.class, sentinel.worker.WorkerUpdate.Builder.class);
  }

  private int bitField0_;
  public static final int WORKER_FIELD_NUMBER = 1;
  private sentinel.worker.Worker worker_;
  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   * @return Whether the worker field is set.
   */
  @java.lang.Override
  public boolean hasWorker() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   * @return The worker.
   */
  @java.lang.Override
  public sentinel.worker.Worker getWorker() {
    return worker_ == null ? sentinel.worker.Worker.getDefaultInstance() : worker_;
  }
  /**
   * <code>.sentinel.worker.Worker worker = 1;</code>
   */
  @java.lang.Override
  public sentinel.worker.WorkerOrBuilder getWorkerOrBuilder() {
    return worker_ == null ? sentinel.worker.Worker.getDefaultInstance() : worker_;
  }

  public static final int UPDATE_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object updateType_ = "";
  /**
   * <code>string update_type = 2;</code>
   * @return The updateType.
   */
  @java.lang.Override
  public java.lang.String getUpdateType() {
    java.lang.Object ref = updateType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateType_ = s;
      return s;
    }
  }
  /**
   * <code>string update_type = 2;</code>
   * @return The bytes for updateType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdateTypeBytes() {
    java.lang.Object ref = updateType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getWorker());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(updateType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, updateType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getWorker());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(updateType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, updateType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof sentinel.worker.WorkerUpdate)) {
      return super.equals(obj);
    }
    sentinel.worker.WorkerUpdate other = (sentinel.worker.WorkerUpdate) obj;

    if (hasWorker() != other.hasWorker()) return false;
    if (hasWorker()) {
      if (!getWorker()
          .equals(other.getWorker())) return false;
    }
    if (!getUpdateType()
        .equals(other.getUpdateType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWorker()) {
      hash = (37 * hash) + WORKER_FIELD_NUMBER;
      hash = (53 * hash) + getWorker().hashCode();
    }
    hash = (37 * hash) + UPDATE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static sentinel.worker.WorkerUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static sentinel.worker.WorkerUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static sentinel.worker.WorkerUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static sentinel.worker.WorkerUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(sentinel.worker.WorkerUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code sentinel.worker.WorkerUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:sentinel.worker.WorkerUpdate)
      sentinel.worker.WorkerUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sentinel.worker.WorkerUpdate.class, sentinel.worker.WorkerUpdate.Builder.class);
    }

    // Construct using sentinel.worker.WorkerUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetWorkerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      worker_ = null;
      if (workerBuilder_ != null) {
        workerBuilder_.dispose();
        workerBuilder_ = null;
      }
      updateType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return sentinel.worker.WorkerOuterClass.internal_static_sentinel_worker_WorkerUpdate_descriptor;
    }

    @java.lang.Override
    public sentinel.worker.WorkerUpdate getDefaultInstanceForType() {
      return sentinel.worker.WorkerUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public sentinel.worker.WorkerUpdate build() {
      sentinel.worker.WorkerUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public sentinel.worker.WorkerUpdate buildPartial() {
      sentinel.worker.WorkerUpdate result = new sentinel.worker.WorkerUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(sentinel.worker.WorkerUpdate result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.worker_ = workerBuilder_ == null
            ? worker_
            : workerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.updateType_ = updateType_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof sentinel.worker.WorkerUpdate) {
        return mergeFrom((sentinel.worker.WorkerUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(sentinel.worker.WorkerUpdate other) {
      if (other == sentinel.worker.WorkerUpdate.getDefaultInstance()) return this;
      if (other.hasWorker()) {
        mergeWorker(other.getWorker());
      }
      if (!other.getUpdateType().isEmpty()) {
        updateType_ = other.updateType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetWorkerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              updateType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private sentinel.worker.Worker worker_;
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.worker.Worker, sentinel.worker.Worker.Builder, sentinel.worker.WorkerOrBuilder> workerBuilder_;
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     * @return Whether the worker field is set.
     */
    public boolean hasWorker() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     * @return The worker.
     */
    public sentinel.worker.Worker getWorker() {
      if (workerBuilder_ == null) {
        return worker_ == null ? sentinel.worker.Worker.getDefaultInstance() : worker_;
      } else {
        return workerBuilder_.getMessage();
      }
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public Builder setWorker(sentinel.worker.Worker value) {
      if (workerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        worker_ = value;
      } else {
        workerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public Builder setWorker(
        sentinel.worker.Worker.Builder builderForValue) {
      if (workerBuilder_ == null) {
        worker_ = builderForValue.build();
      } else {
        workerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public Builder mergeWorker(sentinel.worker.Worker value) {
      if (workerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          worker_ != null &&
          worker_ != sentinel.worker.Worker.getDefaultInstance()) {
          getWorkerBuilder().mergeFrom(value);
        } else {
          worker_ = value;
        }
      } else {
        workerBuilder_.mergeFrom(value);
      }
      if (worker_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public Builder clearWorker() {
      bitField0_ = (bitField0_ & ~0x00000001);
      worker_ = null;
      if (workerBuilder_ != null) {
        workerBuilder_.dispose();
        workerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public sentinel.worker.Worker.Builder getWorkerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetWorkerFieldBuilder().getBuilder();
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    public sentinel.worker.WorkerOrBuilder getWorkerOrBuilder() {
      if (workerBuilder_ != null) {
        return workerBuilder_.getMessageOrBuilder();
      } else {
        return worker_ == null ?
            sentinel.worker.Worker.getDefaultInstance() : worker_;
      }
    }
    /**
     * <code>.sentinel.worker.Worker worker = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        sentinel.worker.Worker, sentinel.worker.Worker.Builder, sentinel.worker.WorkerOrBuilder> 
        internalGetWorkerFieldBuilder() {
      if (workerBuilder_ == null) {
        workerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            sentinel.worker.Worker, sentinel.worker.Worker.Builder, sentinel.worker.WorkerOrBuilder>(
                getWorker(),
                getParentForChildren(),
                isClean());
        worker_ = null;
      }
      return workerBuilder_;
    }

    private java.lang.Object updateType_ = "";
    /**
     * <code>string update_type = 2;</code>
     * @return The updateType.
     */
    public java.lang.String getUpdateType() {
      java.lang.Object ref = updateType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string update_type = 2;</code>
     * @return The bytes for updateType.
     */
    public com.google.protobuf.ByteString
        getUpdateTypeBytes() {
      java.lang.Object ref = updateType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update_type = 2;</code>
     * @param value The updateType to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      updateType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string update_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdateType() {
      updateType_ = getDefaultInstance().getUpdateType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string update_type = 2;</code>
     * @param value The bytes for updateType to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      updateType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sentinel.worker.WorkerUpdate)
  }

  // @@protoc_insertion_point(class_scope:sentinel.worker.WorkerUpdate)
  private static final sentinel.worker.WorkerUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new sentinel.worker.WorkerUpdate();
  }

  public static sentinel.worker.WorkerUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkerUpdate>
      PARSER = new com.google.protobuf.AbstractParser<WorkerUpdate>() {
    @java.lang.Override
    public WorkerUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WorkerUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkerUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public sentinel.worker.WorkerUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

